# Uploads g++ build for linux

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Linux build
        run: g++ -O3 -o lhc.exe src/*.cpp src/**/*.cpp

      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: LHC Linux
          path: lhc
