# Uploads artifacts built with g++

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init g++
        uses: egor-tensin/setup-gcc@v1

      - name: Build
        run: g++ -O3 -o lhc src/*.cpp src/**/*.cpp
      
      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: LHC
          path: lhc
