# Uploads artifacts built with g++

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init g++
        uses: egor-tensin/setup-gcc@v1

      - name: Init MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Linux Build
        run: g++ -O3 -o build/lhc src/*.cpp src/**/*.cpp

      - name: Windows Build
        run: c++ -O3 -o build/lhc_win.exe src/*.cpp src/**/*.cpp

      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: LHC Binaries
          path: build/*
