# Uploads artifacts built with g++

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  MSYSTEM: MINGW64
  MSYS2_PATH_TYPE: inherit
  SCHEME: scheme

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Init g++
        uses: egor-tensin/setup-gcc@v1

      - uses: actions/checkout@v3

      - name: Linux build
        run: g++ -O3 -o lhc src/*.cpp src/**/*.cpp

      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: LHC Linux
          path: lhc

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Windows build
        run: g++ -O3 -o lhc_win.exe src\*.cpp src\**\*.cpp

      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: LHC Windows
          path: lhc_win.exe
